application: netgamixtutorials
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.py
